export const productoSchema = [
  {
    $formkit: "text",
    name: "codigo",
    label: "Código del producto",
    validation: "required|length:3",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "El código es obligatorio",
      length: "Debe tener al menos 3 caracteres",
    },
  },
  {
    $formkit: "text",
    name: "nombre",
    label: "Nombre del producto",
    validation: "required|length:3",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "El nombre es obligatorio",
      length: "Debe tener al menos 3 caracteres",
    },
  },
  {
    $formkit: "textarea",
    name: "descripcion",
    label: "Descripción",
    validation: "required|length:5",
    inputClass: "textarea textarea-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "La descripción es obligatoria",
      length: "Debe tener al menos 5 caracteres",
    },
  },
  {
    $formkit: "text",
    name: "categoria",
    label: "Categoría",
    validation: "required",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "La categoría es obligatoria",
    },
  },
  {
    $formkit: "text",
    name: "proveedor",
    label: "Proveedor",
    validation: "required",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "El proveedor es obligatorio",
    },
  },
  {
    $formkit: "number",
    name: "precio_compra",
    label: "Precio de compra",
    validation: "required|number",
    step: "0.01",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "El precio de compra es obligatorio",
      number: "Debe ser un número válido",
    },
  },
  {
    $formkit: "number",
    name: "precio_venta",
    label: "Precio de venta",
    validation: "required|number",
    step: "0.01",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "El precio de venta es obligatorio",
      number: "Debe ser un número válido",
    },
  },
  {
    $formkit: "text",
    name: "unidad_medida",
    label: "Unidad de medida",
    placeholder: "Ej: kg, lb, unidad, caja",
    validation: "required",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "La unidad de medida es obligatoria",
    },
  },
  {
    $formkit: "number",
    name: "stock_minimo",
    label: "Stock mínimo",
    validation: "required|number",
    inputClass: "input input-bordered w-full",
    outerClass: "mb-4 flex flex-col gap-1",
    validationMessages: {
      required: "El stock mínimo es obligatorio",
      number: "Debe ser un número válido",
    },
  },
];
